name       : gnome-online-miners
version    : 3.26.0
release    : 6
source     :
    - https://download.gnome.org/sources/gnome-online-miners/3.26/gnome-online-miners-3.26.0.tar.xz : 7f404db5eccb87524a5dfcef5b6f38b11047b371081559afbe48c34dbca2a98e
license    : GPL-2.0-only
component  : desktop.gnome.core
summary    : Crawls through your online content
description: |
    Crawls through your online content
builddeps  :
    - pkgconfig(dleyna-server-service-1.0)
    - pkgconfig(grilo-0.3)
    - pkgconfig(libgdata)
    - pkgconfig(libgfbgraph-0.2)
    - pkgconfig(tracker-sparql-2.0)
    - pkgconfig(zapojit-0.0)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
