name       : gnome-online-miners
version    : 3.34.0
release    : 11
source     :
    - https://download.gnome.org/sources/gnome-online-miners/3.34/gnome-online-miners-3.34.0.tar.xz : 845c2260fb12f14315c800d04d60f37e076c7c7b4222587ae75f108562fa52d8
license    : GPL-2.0-or-later
component  : desktop.gnome.core
summary    : Crawls through your online content
description: |
    Crawls through your online content
builddeps  :
    - pkgconfig(dleyna-server-service-1.0)
    - pkgconfig(grilo-0.3)
    - pkgconfig(libgdata)
    - pkgconfig(libgfbgraph-0.2)
    - pkgconfig(tracker-sparql-2.0)
    - pkgconfig(zapojit-0.0)
rundeps    :
    - tracker-miners
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
