name       : gnome-online-miners
version    : 3.20.1
release    : 1
source     :
    - https://download.gnome.org/sources/gnome-online-miners/3.20/gnome-online-miners-3.20.1.tar.xz : fd67b9abad6233689a921d84dbe583a8b89d5ade7f1b5d2f348493888baa3429
license    : GPL-2.0
component  : desktop.gnome.core
summary    : Crawls through your online content
description: |
    Crawls through your online content
builddeps  :
    - pkgconfig(dleyna-server-service-1.0)
    - pkgconfig(grilo-0.3)
    - pkgconfig(libgdata)
    - pkgconfig(libgfbgraph-0.2)
    - pkgconfig(tracker-miner-1.0)
    - pkgconfig(zapojit-0.0)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
